### ISSUE TITLE
Not working on macOS Big Sur / v11.4

### ISSUE THREAD

**Issue by carlisia** [ptsochantaris/trailer-cli#11]
See the error below.

Trailer: v1.1.2.

Been finding this answer in multiple places: 

[bad CPU type in executable in Catalina - Apple Community](https://discussions.apple.com/thread/251024475?answerId=251937368022#251937368022)

```
➜  trailer
Failed to execute process '/usr/local/bin/trailer'. Reason:
exec: Bad CPU type in executable
```

**Comment by ptsochantaris** [comment]
Yikes, the binary for 1.1.2 was compiled for M1 Macs only - sorry! I've replaced it now with a binary that should have both architectures: https://github.com/ptsochantaris/trailer-cli/releases/download/1.1.2/trailer.zip

Let me know if you continue to have trouble with it.

**Comment by carlisia** [comment]
That worked, thank you so much!!
