### ISSUE TITLE
Unable to get started…

### ISSUE THREAD

**Issue by halostatue** [ptsochantaris/trailer-cli#12]
This happens with `trailer update all` or `trailer update prs`:

```console
$ trailer update prs -debug
…
PRs fragment checkFields on CheckRun { __typename id name conclusion startedAt completedAt permalink } { node(id: "PR_kwDOACCCtM5Yw1bu") { ... on PullRequest { checkRuns(first: 20, after: "Y3Vyc29yOnYyOpHPAAAAA8gEA_Q=") { edges { node { __typename ... checkFields } cursor } pageInfo { hasNextPage } } } } rateLimit { limit cost remaining resetAt nodeCount } }
PRs Failed with error: 'Field 'checkRuns' doesn't exist on type 'PullRequest''
```

As a side note, the update *failed*, but the exit code is zero.

**Comment by ptsochantaris** [comment]
Hi! Sorry for the slow reply - this error suggests that perhaps you're trying to pull from a server that doesn't have support for GitHub Checks? Or could it be perhaps that your access token does not provide access to that info?

**Comment by halostatue** [comment]
I’m not sure as this was a while ago and I uninstalled trailer-cli not long after. I’m pretty sure that I set up my access token with the appropriate access data and I do not have an alternate server (I’m only using GitHub.com).

**Comment by ptsochantaris** [comment]
No worries, thanks for the info anyway! I'll definitely keep an eye out for it 👍
