### ISSUE TITLE
Add the branch name on `show pr` command

### ISSUE THREAD

**Issue by danillos** [ptsochantaris/trailer-cli#2]
Would be good to see the branch name there.

btw, Great work @ptsochantaris

**Comment by ptsochantaris** [comment]
This makes total sense, will add it right now. Thanks for the suggestion!

**Comment by ptsochantaris** [comment]
Here's a build that does this (it will require a `trailer update all` in order to store the new info though).

Let me know if this is what you had in mind!

[trailer.zip](https://github.com/ptsochantaris/trailer-cli/files/1482815/trailer.zip)

**Comment by danillos** [comment]
Wow, that was fast and it is working like a charm.

Thank you @ptsochantaris

**Comment by ptsochantaris** [comment]
Excellent!

It involved adding one field, so it was very simple, and it's something I'd like to see too - So why prolong the inevitable :) (https://github.com/ptsochantaris/trailer-cli/commit/f94bf0d4a3a3ec5d827ca1e7b6d9d5afde9851b4)

(Also, I forgot to thank you for your nice comment, so, thanks! I'm very glad you're finding this tool useful.)

**Comment by danillos** [comment]
I'm starting to use it to improve my development time. The branch name was the first thing that I notice that was missing and I had to open the browser to see the name. =/

**Comment by ptsochantaris** [comment]
Yes, this was definitely a very easy and (in retrospect!) obvious win, please do feel free to offer more suggestions as you work with it!

**Comment by ptsochantaris** [comment]
(BTW note that if you want to open a browser, you can use `trailer open pr X` to quickly get there)

**Comment by ptsochantaris** [comment]
Going to close this for now, as the feature is on a release build, but feel free to suggest changes to this feature in a new issue if you like.
