### ISSUE TITLE
Be able to select which fields show on the `list prs` command

### ISSUE THREAD

**Issue by danillos** [ptsochantaris/trailer-cli#3]
Something like: `trailer list prs -number -url -user -title`

**Comment by ptsochantaris** [comment]
This makes a lot of sense. However, some of these parameters can be confused with filtering options (for instance -number filters the list to limit to items with that number).

However, I'm thinking this could be a parameter in itself:
`-display:number,url,author,title,repo,branch[,etc]`

Specifying this parameter could override the defaults, so `-columns:number,title` would mean that only those would be displayed, or for some reason `-columns:number` would only show the number, and so on.

What do you think of this?

**Comment by danillos** [comment]
I liked it.

Another suggestion that could be good is use it like a template system like:

`-format "[{numbe}] - {title} ({author})"`
`-format json` :thinking: 

So anyone can format it for their own needs

**Comment by ptsochantaris** [comment]
Interesting! Thinking a bit about it, I have to admit I would be a bit hesitant to do this as templating _inside the tool itself_ to be honest. On the other hand, the usefulness of what you suggest is very clear and obvious.

As a command line tool, I'm starting to think it ideally ought to be the source of info which could then be easily piped into another tool that can perform the templating...

What if it is something like `-csv:number,url,author,title,repo,branch[,etc]` which would output the specified fields as a non-highlighted comma-separated list, which can then be piped into another tool whose specialty is to format CSV into anything you like (for example, sed, or something advanced like CSVkit: http://csvkit.readthedocs.io/en/1.0.2/)

What would your thoughts be on something like that?

**Comment by ptsochantaris** [comment]
(Also, `-format json` is a good thought - I'm just wondering how typographically process-able it is, given that if you want to load JSON you can use the data in the `~/.trailer` directory anyway)

**Comment by danillos** [comment]
If you want this CLI to be a source of info, I agree with you. It makes sense to not have any Template System inside of it and should output in formats that can be processed later like JSON, CSV, XML...

But in my opinion, currently. It is not what this CLI is doing right now. 

Look this image:

![desc](https://camo.githubusercontent.com/3ef9693f0f8dfdf4b70efb0a10195bfd0003139a/68747470733a2f2f7261772e6769746875622e636f6d2f7074736f6368616e74617269732f747261696c65722f67682d70616765732f747261696c65722d636c692d73637265656e73686f742e6a7065673f7261773d74727565)

The outputs were specially formatted for Humans, and it is one of the reasons that I'm using it.

It is easy and fast, I just need to run a small command, and it gives me a readable output.

But of course will be good to have a processable format of the output too.

I liked this CLI you did a great job. My suggestion is to continue doing what it is doing now but giving more flexibility to the users.

**Comment by ptsochantaris** [comment]
What you're saying here definitely makes sense, I get your argument.

In which case though, if we don't want to template, and I think you've definitely talked me into that :) I would probably not want to have a half-way template either, and go directly with pre-formatted fields for each column. 

Something like this, if all fields were turned on (with the default being the same as now):
`>` `TYPE` `NUMBER` `Title` (`repo name`) (`branch`) (@`author`) (Created: `created date`) (Updated: `updated date`) `url`

(url would be with no delimiter to make it easier to copy/paste/click)

Can you think of other columns that could potentially fit in well on this list?

**Comment by danillos** [comment]
Maybe `labels`, What do you think?



`> PR 1234 Feature name (branch-name) [label 1] [label 2]`

**Comment by ptsochantaris** [comment]
True, `labels` is a good one 👍

**Comment by ptsochantaris** [comment]
Have a go with v1.0.5, it now includes a `-fields` parameter to specify a custom list of fields.

**Comment by ptsochantaris** [comment]
Hi, going to close this for now as it's in the release build, but feel free to re-open or add new issues!
