### ISSUE TITLE
make available via homebrew

### ISSUE THREAD

**Issue by jhopperzw** [ptsochantaris/trailer-cli#8]
this would be a nice to install via homebrew

**Comment by ptsochantaris** [comment]
You're right, will look into it 👍

**Comment by ptsochantaris** [comment]
Well it took close to 3 years but I hate to have an issue pending :D So from today you can install trailer-cli by doing
```
brew install ptsochantaris/tap/trailer-cli
```
I'll update the docs shortly to make installation on macOS a little saner, and possibly add some bottles as well.
